{% set version = "4.36.0" %}
{% set sha256 = "14860b73118ac140b7a3f55446890c777d1b67149cb024279fe3710dad7f535c" %}

package:
  name: breathe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/breathe/breathe-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
    # Detects sphinx at build time
    - sphinx >=4.0,<9.0.0a0
  run:
    - python >={{ python_min }}
    - sphinx >=4.0,<9.0.0a0
    - docutils >=0.12
    - Jinja2 >=2.7.3
    - MarkupSafe >=0.23
    - Pygments >=1.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - breathe

about:
  home: https://github.com/breathe-doc/breathe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension to reStructuredText and Sphinx to be able to read and render the Doxygen xml output.

  description: |
    Breathe provides a bridge between the Sphinx and Doxygen documentation systems.

    It is an easy way to include Doxygen information in a set of documentation
    generated by Sphinx. The aim is to produce an autodoc like support for
    people who enjoy using Sphinx but work with languages other than Python.
    The system relies on the Doxygen’s xml output.
  doc_url: http://breathe.readthedocs.io/
  dev_url: https://github.com/breathe-doc/breathe

extra:
  recipe-maintainers:
    - AA-Turner
    - SylvainCorlay
    - JohanMabille
    - hmaarrfk
