{% set name = "breathe" %}
{% set version = "4.14.0" %}
{% set sha256 = "178848e4088faf8c2c60f000379fcabfb3411b260e0fbddc08fb57e0e5caea08" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - sphinx >=1.4
    - docutils >=0.5
    - six >=1.4

test:
  imports:
    - breathe

about:
  home: https://github.com/michaeljones/breathe
  license: BSD
  summary: 'An extension to reStructuredText and Sphinx to be able to read and render the Doxygen xml output.'

  description: |
    Breathe provides a bridge between the Sphinx and Doxygen documentation systems.

    It is an easy way to include Doxygen information in a set of documentation
    generated by Sphinx. The aim is to produce an autodoc like support for
    people who enjoy using Sphinx but work with languages other than Python.
    The system relies on the Doxygen’s xml output.
  doc_url: http://breathe.readthedocs.io/
  dev_url: https://github.com/michaeljones/breathe

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
